---
openapi: 3.0.1
info:
  title: Example API V1
  version: v1
paths:
  api/v1/houses:
    post:
      summary: create an house
      tags:
      - houses
      parameters: []
      responses:
        '201':
          description: house created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/house"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_house"
components:
  schemas:
    errors_not_found:
      type: object
      properties:
        message:
          type: string
          example: Record Not Found
    errors_object:
      type: object
      properties:
        errors:
          "$ref": "#/components/schemas/errors_map"
    errors_map:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    new_house:
      type: object
      description: A house is a building
      properties:
        name:
          type: string
          description: The house's name.
          example: My home
        address:
          type: string
          description: The house's address.
          example: 46 rue Paradis, 13006 Marseille
        user_id:
          type: integer
          readOnly: true
          minimum: 1
          description: The unique identifier of the house's user
          example: 1
      required:
      - name
      - address
    edit_house:
      type: object
      description: A house is a building
      properties:
        name:
          type: string
          description: The house's name.
          example: My home
        address:
          type: string
          description: The house's address.
          example: 46 rue Paradis, 13006 Marseille
        user_id:
          type: integer
          readOnly: true
          minimum: 1
          description: The unique identifier of the house's user
          example: 1
      required:
      - name
      - address
    house:
      type: object
      description: A house is a building
      properties:
        id:
          type: integer
          readOnly: true
          minimum: 1
          description: The unique identifier of an house
          example: 1
        user_id:
          type: integer
          readOnly: true
          minimum: 1
          description: The unique identifier of the house's user
          example: 1
        name:
          type: string
          description: The house's name.
          example: My home
        address:
          type: string
          description: The house's address.
          example: 46 rue Paradis, 13006 Marseille
        longitude:
          type: string
          description: 'Coordinates: Longitude'
          example: "-73.4924,45.5458"
        latitude:
          type: string
          description: 'Coordinates: Latitude'
          example: "-73.4924,45.5458"
        created_at:
          type: string
          description: Creation timestamp.
          format: date-time
        updated_at:
          type: string
          description: Last update timestamp.
          format: date-time
      required:
      - id
      - user_id
      - name
      - address
      - created_at
      - updated_at
